name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Check if src directory exists
      run: |
        if [ -d "src" ]; then
          echo "src directory exists."
        else
          echo "Error: src directory does not exist."
          exit 1
        fi

    - name: Run tests
      run: |
        cd src
         python -m pytest -v addition.py
